'use client';

import React from 'react';
import { useRouter } from 'next/navigation';
import { 
  ArrowLeft, 
  Cpu, 
  Layers, 
  GitBranch, 
  Activity, 
  BookOpen, 
  Code, 
  Settings, 
  Database,
  Eye,
  Rocket
} from 'lucide-react';
import CanvasGrid from '../../components/ui/canvas-grid';
import ChronosLogo from '../../components/branding/chronos-logo';

export default function DeveloperPortal() {
  const router = useRouter();

  const techStack = [
    { name: 'Next.js 15 (App Router)', role: 'Frontend Core & Routing Framework', category: 'Frontend' },
    { name: 'React 19 & TypeScript', role: 'Component UI & Strict System Typing', category: 'Frontend' },
    { name: 'Tailwind CSS & CSS Grid', role: 'Responsive layout and era-themed styles', category: 'Frontend' },
    { name: 'Framer Motion', role: 'High-fidelity animations & smooth drawers', category: 'Frontend' },
    { name: 'Lucide Icons', role: 'Modern UI vector icons', category: 'Frontend' },
    { name: 'Express & Node.js', role: 'Backend API & Generation Pipeline Orchestrator', category: 'Backend' },
    { name: 'Supabase (PostgreSQL)', role: 'Persistent storage of timelines, events, personas, and feeds', category: 'Database' },
    { name: 'Google Generative AI (Gemini)', role: 'Generative simulation engine powering alternate histories', category: 'AI Components' },
  ];

  const features = [
    { title: 'Reality Divergence Console', desc: 'Accepts free-form prompt anchors (e.g. "What if Rome never fell?") and triggers multi-stage simulation pipeline.' },
    { title: 'Chronological Timeline Generator', desc: 'Creates a set of historical pivot events establishing the path of divergence.' },
    { title: 'Persona Dossier Compiler', desc: 'Simulates active historical figures, complete with names, roles, influence scores, and themed biographies.' },
    { title: 'Polysocial Live Feed Stream', desc: 'Renders interleaved posts, ads, and news items matching the exact era theme (Cyberpunk, Steampunk, etc.).' },
    { title: 'Seeded Fallback Sandbox', desc: 'Ensures safe offline local development when API credentials/keys are missing.' },
    { title: 'Interactive Comments Drawer', desc: 'Allows users to view communication threads generated by simulated personas on feed posts.' },
  ];

  const versionHistory = [
    { version: 'v1.0.0', date: 'June 2026', title: 'UI/UX Improvement & Brand Refresh', desc: 'Introduced manual pagination, comment systems, content interleaving engine, stacked telemetry views, and developer console.' },
    { version: 'v0.5.0', date: 'May 2026', title: 'Comments Generation Pipeline', desc: 'Added backend templates and AI prompts to generate contextually relevant persona replies on feed posts.' },
    { version: 'v0.4.0', date: 'April 2026', title: 'Polymorphic Frontend Client', desc: 'Connected landing console and timelines to live backend feeds with polling hooks and theme era selectors.' },
    { version: 'v0.3.0', date: 'March 2026', title: 'Pipeline Orchestration API', desc: 'Wired Express POST routes to database-driven generation loops and status polling handlers.' },
    { version: 'v0.2.0', date: 'February 2026', title: 'Seeded Prompt Chain Framework', desc: 'Developed clean JSON parser utilities and engineered multi-turn prompts for worlds, personas, and news.' },
    { version: 'v0.1.0', date: 'January 2026', title: 'Project Initialization', desc: 'Configured Supabase db schemas, base environments, strict types, and sandbox mock tests.' },
  ];

  const reposStats = [
    { label: 'Programming Language', value: 'TypeScript (100%)' },
    { label: 'Design System', value: 'Vanilla Tailwind CSS v4' },
    { label: 'Era Themes Support', value: 'Steam, Roman, Mars, Default' },
    { label: 'Target Viewports', value: 'Desktop, Tablet, Mobile (Fully Fluid)' },
    { label: 'Offline Sandbox Mode', value: 'Enabled (Automatic fallback)' },
  ];

  return (
    <div className="min-h-screen relative flex flex-col p-4 md:p-6 select-none overflow-x-hidden pb-16">
      <CanvasGrid />

      {/* Header */}
      <header className="w-full max-w-6xl mx-auto flex items-center justify-between border-b border-white/5 pb-4 mb-8 z-10">
        <div className="flex items-center gap-3">
          <button
            onClick={() => router.push('/')}
            className="w-9 h-9 rounded-full border border-white/10 hover:border-accent-base bg-white/5 flex items-center justify-center text-text-dim hover:text-text-main cursor-pointer hover:shadow-[0_0_8px_rgba(var(--glow-color),0.2)] transition-all"
          >
            <ArrowLeft size={16} />
          </button>
          <div>
            <h1 className="text-xl font-bold font-serif text-text-main tracking-tight leading-none flex items-center gap-2">
              <ChronosLogo size={20} className="text-primary-base" />
              Developer Portal
            </h1>
            <span className="text-[10px] font-mono text-accent-base uppercase tracking-wider">
              Simulation Core Documentation & Architecture
            </span>
          </div>
        </div>
        <div className="hidden md:flex gap-4 font-mono text-[10px] text-text-dim">
          <span>PORTAL: ONLINE</span>
          <span className="text-emerald-400">SECURE ACCESS</span>
        </div>
      </header>

      {/* Main Grid */}
      <main className="flex-1 w-full max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-12 gap-8 z-10 relative">
        {/* Left column: Overview, Stack & Stats (7 Cols) */}
        <div className="md:col-span-7 flex flex-col gap-8">
          {/* Project Overview */}
          <section className="glass-panel p-6 rounded-2xl border border-border-color flex flex-col gap-4">
            <h2 className="text-sm font-bold font-mono uppercase tracking-wider text-text-main flex items-center gap-2">
              <Cpu size={16} className="text-accent-base" />
              1. Project Overview & Meta
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs font-sans">
              <div className="glass-panel p-4 rounded-xl bg-white/[0.02] border border-white/5">
                <span className="font-bold text-accent-base block mb-1">Built For</span>
                <p className="text-text-dim leading-relaxed">
                  Alternate history simulation testing, evaluating multi-stage generative models and timeline consistency algorithms.
                </p>
              </div>
              <div className="glass-panel p-4 rounded-xl bg-white/[0.02] border border-white/5">
                <span className="font-bold text-accent-base block mb-1">Built By</span>
                <p className="text-text-dim leading-relaxed">
                  Antigravity AI (Pair Programming with Google DeepMind SDK Client).
                </p>
              </div>
            </div>
          </section>

          {/* Tech Stack List */}
          <section className="glass-panel p-6 rounded-2xl border border-border-color flex flex-col gap-4">
            <h2 className="text-sm font-bold font-mono uppercase tracking-wider text-text-main flex items-center gap-2">
              <Layers size={16} className="text-accent-base" />
              2. Simulation Tech Stack
            </h2>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {techStack.map((tech, i) => (
                <div key={i} className="flex flex-col p-3 border border-white/5 rounded-xl bg-white/[0.01] hover:bg-white/[0.03] transition-colors">
                  <span className="font-mono text-[10px] text-accent-base uppercase tracking-wider">{tech.category}</span>
                  <span className="font-bold text-text-main text-xs mt-0.5">{tech.name}</span>
                  <span className="text-[10px] text-text-dim mt-1 font-sans leading-normal">{tech.role}</span>
                </div>
              ))}
            </div>
          </section>

          {/* Features Showcase */}
          <section className="glass-panel p-6 rounded-2xl border border-border-color flex flex-col gap-4">
            <h2 className="text-sm font-bold font-mono uppercase tracking-wider text-text-main flex items-center gap-2">
              <BookOpen size={16} className="text-accent-base" />
              3. Feature Architecture List
            </h2>
            <div className="space-y-3 font-sans text-xs">
              {features.map((feat, i) => (
                <div key={i} className="p-3.5 border border-white/5 rounded-xl bg-white/[0.02]">
                  <span className="font-bold text-text-main block">{feat.title}</span>
                  <p className="text-text-dim mt-1 leading-relaxed">{feat.desc}</p>
                </div>
              ))}
            </div>
          </section>
        </div>

        {/* Right column: Architecture, Git Milestones & Stats (5 Cols) */}
        <div className="md:col-span-5 flex flex-col gap-8">
          {/* Architecture Overview */}
          <section className="glass-panel p-6 rounded-2xl border border-border-color flex flex-col gap-4">
            <h2 className="text-sm font-bold font-mono uppercase tracking-wider text-text-main flex items-center gap-2">
              <Activity size={16} className="text-accent-base" />
              4. System Architecture
            </h2>
            <div className="space-y-4 font-mono text-[10px] text-text-dim">
              <div className="border border-white/5 rounded-xl p-3 bg-white/[0.02]">
                <span className="text-accent-base font-bold uppercase block mb-1 flex items-center gap-1">
                  <Code size={12} />
                  Backend Generation Pipeline
                </span>
                <p className="font-sans leading-relaxed text-[11px]">
                  Takes an anchor prompt and utilizes Gemini Flash via structured temperature steps to compile the timeline, personas, news, advertisements, and feed posts. Resulting datasets are stored securely in Supabase.
                </p>
              </div>

              <div className="border border-white/5 rounded-xl p-3 bg-white/[0.02]">
                <span className="text-accent-base font-bold uppercase block mb-1 flex items-center gap-1">
                  <Database size={12} />
                  Timeline Generation Flow
                </span>
                <p className="font-sans leading-relaxed text-[11px]">
                  1. POST /api/worlds triggers stub compilation.
                  2. World profile generation (name, era, tech level, gov type).
                  3. Divergence chronology events generation (3 steps).
                  4. Persona profiles generation (4 key figures).
                  5. Feed cards (posts, news, ads, and comment replies) generation.
                </p>
              </div>

              <div className="border border-white/5 rounded-xl p-3 bg-white/[0.02]">
                <span className="text-accent-base font-bold uppercase block mb-1 flex items-center gap-1">
                  <Eye size={12} />
                  AI Components & Controls
                </span>
                <p className="font-sans leading-relaxed text-[11px]">
                  Uses prompt engineering prompts for structured JSON replies, safety filter fallbacks, and content cleaning regexes to extract generative responses reliably.
                </p>
              </div>
            </div>
          </section>

          {/* Repository Statistics */}
          <section className="glass-panel p-6 rounded-2xl border border-border-color flex flex-col gap-4">
            <h2 className="text-sm font-bold font-mono uppercase tracking-wider text-text-main flex items-center gap-2">
              <Settings size={16} className="text-accent-base" />
              5. Repository Statistics
            </h2>
            <div className="flex flex-col gap-2 font-mono text-xs">
              {reposStats.map((stat, i) => (
                <div key={i} className="flex justify-between items-center border-b border-white/5 pb-2 last:border-0 last:pb-0">
                  <span className="text-text-dim uppercase text-[10px]">{stat.label}</span>
                  <span className="text-text-main font-bold">{stat.value}</span>
                </div>
              ))}
            </div>
          </section>

          {/* Major Milestones Timeline */}
          <section className="glass-panel p-6 rounded-2xl border border-border-color flex flex-col gap-4">
            <h2 className="text-sm font-bold font-mono uppercase tracking-wider text-text-main flex items-center gap-2">
              <GitBranch size={16} className="text-accent-base" />
              6. Milestones & Git Version History
            </h2>
            <div className="relative border-l border-white/10 ml-2.5 pl-4 space-y-5">
              {versionHistory.map((item, i) => (
                <div key={i} className="relative group">
                  {/* Point node */}
                  <div className="absolute -left-[22px] top-1.5 w-3 h-3 rounded-full border border-accent-base bg-background group-hover:bg-accent-base transition-colors" />
                  
                  <div className="flex flex-col">
                    <div className="flex items-baseline gap-2">
                      <span className="font-mono text-xs font-bold text-accent-base">{item.version}</span>
                      <span className="text-[9px] font-mono text-text-dim">{item.date}</span>
                    </div>
                    <span className="text-xs font-bold text-text-main font-serif mt-0.5">{item.title}</span>
                    <p className="text-[10px] text-text-dim leading-relaxed font-sans mt-1">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Future Roadmap */}
          <section className="glass-panel p-6 rounded-2xl border border-border-color flex flex-col gap-4">
            <h2 className="text-sm font-bold font-mono uppercase tracking-wider text-text-main flex items-center gap-2">
              <Rocket size={16} className="text-accent-base" />
              7. Future Simulation Roadmap
            </h2>
            <div className="space-y-2.5 font-sans text-xs text-text-dim">
              <div className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-accent-base mt-1.5 flex-shrink-0" />
                <span>Simulated Persona Direct Messaging: Real-time interactive AI chat with simulated historical figures.</span>
              </div>
              <div className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-accent-base mt-1.5 flex-shrink-0" />
                <span>Dynamic Timeline Branching: Let users inject new events mid-timeline and branch existing worlds.</span>
              </div>
              <div className="flex items-start gap-2">
                <span className="w-1.5 h-1.5 rounded-full bg-accent-base mt-1.5 flex-shrink-0" />
                <span>Alternate Media Generation: Auto-generate themed memes, mechanical drawings, and historical portraits.</span>
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
